# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'StoryIoT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for StoryIoT
  pod 'Alamofire', '4.8.0'

  target 'StoryIoTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
